name: 部署 Storybook 文档

on:
  # 当 docs 目录或 UI 库目录中的文件发生变化时触发
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "packages/versakit-ui/**"

  # 允许手动触发工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: write

jobs:
  build-and-deploy:
    name: 构建并部署 Storybook
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 设置 pnpm
      - name: 设置 pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      # 设置 Node.js
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      # 安装依赖并构建
      - name: 安装依赖并构建
        run: |
          pnpm install
          pnpm install -w
          cd docs && pnpm install
          cd .. && pnpm ui:build
          cd docs && pnpm run build

      # 部署到 GitHub Pages
      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/storybook-static
          branch: gh-pages
          clean: true

      # 显示部署 URL
      - name: 显示部署 URL
        run: |
          echo "文档已部署到 https://versakit.github.io/Versakit-React/storybook/"
