name: 部署 Storybook 文档

on:
  # 当 docs 目录或 UI 库目录中的文件发生变化时触发
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "packages/versakit-ui/**"

  # 允许手动触发工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: write
  pages: write
  id-token: write

# 环境变量
env:
  # 启用 GitHub Pages 部署
  ENABLE_GITHUB_PAGES: true

# 并发控制
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 构建作业
  build:
    name: 构建 Storybook
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v4

      # 设置 pnpm
      - name: 设置 pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      # 设置 Node.js
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      # 安装根目录依赖
      - name: 安装根目录依赖
        run: pnpm install

      # 安装子包目录依赖
      - name: 安装子包目录依赖
        run: pnpm install -w

      # 安装 docs 目录依赖
      - name: 安装 docs 目录依赖
        run: cd docs && pnpm install

      # 构建 UI 库
      - name: 构建 UI 库
        run: pnpm ui:build

      # 构建 Storybook
      - name: 构建 Storybook
        run: cd docs && pnpm run build

      # 部署到 gh-pages 分支
      - name: 部署到 gh-pages 分支
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/storybook-static
          clean: true
          target-folder: storybook
          commit-message: "docs: 更新 Storybook 文档 [skip ci]"

      # 配置 Pages
      - name: 配置 Pages
        uses: actions/configure-pages@v4

      # 上传 Pages 构建制品
      - name: 上传 Pages 制品
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/storybook-static
          name: github-pages

  # 部署作业
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # 输出部署 URL
      - name: 输出部署 URL
        run: |
          echo "文档已部署到 ${{ steps.deployment.outputs.page_url }}storybook/"
